version: "3.8"

services:
    postgres:
        container_name: dc-postgres
        env_file:
            - postgres.env
        healthcheck:
            test: 
                - "CMD-SHELL"
                - "pg_isready --dbname $${POSTGRES_DB} --username $${POSTGRES_USER}"
            interval: 1s
            timeout: 1s
            retries: 5
            start_period: 5s
        image: postgres:alpine
        networks:
            - nw-postgres
        ports:
            - 5432:5432
        restart: always
        tty: true
        volumes:
            - ./postgres-data:/var/lib/postgresql/data
            - ./postgres-initdb.d:/docker-entrypoint-initdb.d

networks:
    nw-postgres:
        driver: bridge
