version: "3"
services:
    postgres:
        container_name: dc-postgres
        env_file:
            postgres.env
        image: postgres:alpine
        networks:
            - nw-postgres
        ports:
            - 5432:5432
        restart: always
        tty: true
        volumes:
            - ./postgres-data:/var/lib/postgresql/data
networks:
    nw-postgres:
        driver: bridge

